apiVersion: v1
kind: Namespace
metadata:
  name: muminio-namespace-2
---
apiVersion: muminio.benien.dev/v1alpha1
kind: MuminioBucket
metadata:
  name: bucket2
  namespace: muminio-namespace-2
spec:
  secretName: bucket2-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: bucket2-secret
  namespace: muminio-namespace-2
data:
  accessKey: dXNlcjEyMzQ=
  secretKey: ZG9udGtub3dyZWFscGFzc3dvcmQ=
type: Opaque
---
