apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: muminiobuckets.muminio.benien.dev
spec:
  group: muminio.benien.dev
  names:
    kind: MuminioBucket
    listKind: MuminioBucketList
    plural: muminiobuckets
    singular: muminiobucket
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MuminioBucket is the Schema for the muminiobuckets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MuminioBucketSpec defines the desired state of MuminioBucket
          properties:
            secretName:
              maxLength: 63
              minLength: 8
              pattern: '[A-Z-a-z][A-Za-z0-9-]+'
              type: string
          type: object
        status:
          description: MuminioBucketStatus defines the observed state of MuminioBucket
          properties:
            minioAccessKey:
              type: string
            minioURL:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
