apiVersion: apps/v1
kind: Deployment
metadata:
  name: muminio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: muminio
  template:
    metadata:
      labels:
        name: muminio
    spec:
      serviceAccountName: muminio
      containers:
        - name: muminio
          # Replace this with the built image name
          image: keaphyra/muminio-operator
          command:
          - muminio
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "muminio"
