name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        go build -v -o build/_output/bin/muminio cmd/manager/main.go
        docker build build/ -t $DOCKER_USER/muminio-operator:$GITHUB_SHA
        docker tag $DOCKER_USER/muminio-operator:$GITHUB_SHA $DOCKER_USER/muminio-operator:latest
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/muminio-operator:$GITHUB_SHA
        docker push $DOCKER_USER/muminio-operator:latest


